#!/usr/bin/env -S sh -c 'docker build --rm -t kungfu.azurecr.io/mw-deepspeed-tenplex:latest -f $0 .'

FROM kungfu.azurecr.io/mw-deepspeed:latest

USER root

# Tenplex
ADD . /workspace/tenplex
RUN cd /workspace/tenplex && \
    pip install .
