# ansible-playbook -i hosts.txt ansible/tenplex.yml

- name: install tenplex 
  hosts: all

  tasks:
  - import_tasks: pull_image.yml

  #- debug: msg="{{ log.stdout }}"
  #- debug: msg="{{ log.stderr }}"
