# ansible-playbook -i hosts.txt ansible/tenplex.yml

- name: install tenplex
  hosts: all

  tasks:
  - import_tasks: ../../ansible/uninstall.yml
  - import_tasks: ../../ansible/install.yml
  - import_tasks: add_group.yml
  - import_tasks: pull_image.yml

  #- debug: msg="{{ log.stdout }}"
  #- debug: msg="{{ log.stderr }}"
