# ansible-playbook -i hosts.txt ansible/tenplex.yml

- name: install tenplex
  hosts: all
  tasks:
  # - import_tasks: ./uninstall.yml
  - import_tasks: ./install.yml

  - debug: msg="{{ log.stdout }}"
  - debug: msg="{{ log.stderr }}"
