- name: check UID
  ignore_errors: yes
  ansible.builtin.shell:
    cmd: id
  register: log

- name: docker ps
  ignore_errors: yes
  ansible.builtin.shell:
    cmd: docker ps
  register: log

- name: pull docker image
  ignore_errors: yes
  ansible.builtin.shell:
    cmd: docker pull kungfu.azurecr.io/mw-megatron-lm-23.06-update-v100
  register: log
