name: Python

on:
- push
- pull_request

jobs:
  test:
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-22.04

    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
    env:
      PYTHONWARNINGS: 'ignore'

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    # - run: pip install -r tests/requirements.txt
    # - run: pip install torch==1.5

    # FIXME: --no-index
    # ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
    # ERROR: No matching distribution found for setuptools>=40.8.0
    # - run: pip install --no-index .
    - run: pip install .

    # TODO: run tests
