name: Python

on:
- push
- pull_request

jobs:
  test:
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-22.04

    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
    env:
      PYTHONWARNINGS: 'ignore'

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    # - run: pip install -r tests/requirements.txt
    # - run: pip install torch==1.5

    # FIXME: --no-index
    # ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
    # ERROR: No matching distribution found for setuptools>=40.8.0
    # - run: pip install --no-index .
    - run: pip install .

    - run: make
    - run: make deb
    - run: |
        DEB=`ls build/*.deb`
        sudo dpkg -i $DEB
    - run: sudo systemctl start mlfs
    - run: mlfs info
    - run: wget https://tenplex.blob.core.windows.net/public/data/train.tf_record
    - run: mlfs-build-tf-index train.tf_record
    - run: mlfs-edit-index -index-url a.idx.txt -o b.idx.txt -from 'train.tf_record' -to 'https://tenplex.blob.core.windows.net/public/data/train.tf_record'
    - run: mlfs mount -global-batch-size 23 -dp-size 4 -idx-name squad1 -index-url file://$PWD/b.idx.txt
    - run: mlfs fetch -file 'https://tenplex.blob.core.windows.net/public/data/train.tf_record' -md5 67eb6da21920dda01ec75cd6e1a5b8d7

    # TODO: run tests
